### ISSUE TITLE
Improve the codesandbox example display

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-angular#2]
Currenlty the codesandbox example does not show a nice search bar (in terms of design):

<img width="721" alt="Capture d’écran 2021-02-12 à 12 36 08" src="https://user-images.githubusercontent.com/20380692/107763522-0cc41680-6d2f-11eb-9bbe-5ee79e307a3b.png">

Wouldn't it be better to display two results only in a single line like for the other codesandbox examples?

<img width="693" alt="Capture d’écran 2021-02-12 à 12 38 04" src="https://user-images.githubusercontent.com/20380692/107763641-39782e00-6d2f-11eb-85ea-409508875b8a.png">

**Comment by bidoubiwa** [comment]
It has been fixed: https://codesandbox.io/s/im-angularis-7xipe?file=/src/main.ts:0-48
could you confirm this is what you want?

**Comment by curquiza** [comment]
Awesome!!!!
