### ISSUE TITLE
Display facets in codesandbox example

### ISSUE THREAD

**Issue by curquiza** [meilisearch/meilisearch-angular#3]
The display of facets could be improved by adding a space between the facet name and the number of facets:

<img width="202" alt="Capture d’écran 2021-02-17 à 13 34 38" src="https://user-images.githubusercontent.com/20380692/108205106-e7ffe280-7124-11eb-981c-d115b9c1d23f.png">

**Comment by bidoubiwa** [comment]
Fixed!
